# Generated by Django 4.2.17 on 2025-02-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cc_wordcloud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='numeric_id',
            new_name='code',
        ),
    ]
