apiVersion: v1
kind: Service
metadata:
  name: cc-backend-service
  namespace: cc-namespace
spec:
  type: LoadBalancer
  selector:
    app: cc-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080