apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc-webapp
  template:
    metadata:
      labels:
        app: cc-webapp
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: cc-webapp
        image: webappacr143101a.azurecr.io/cc_webapp:latest # ACR Image
        ports:
        - containerPort: 8080
        env:
        - name: VITE_APP_API_URL
          value: "http://50.85.88.155/api" # URL zum Backend
        - name: VITE_APP_WS_UR
          value: "hhtp://50.85.88.155/api" # URL zum Backend
        - name: VITE_APP_FRONTEND_URL
          value: "http://50.85.88.155" # URL zum Backend