apiVersion: v1
kind: Service
metadata:
  name: cc-webapp-service
  namespace: cc-namespace
spec:
  type: LoadBalancer
  selector:
    app: cc-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000