name: Terraform Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set Terraform environment variables
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Create Resource Group
        run: az group create --name webapp-backend-rg --location "West Europe"

      - name: Create Storage Account
        run: az storage account create --name webapptfstate143101a --resource-group webapp-backend-rg --location "West Europe" --sku Standard_LRS

      - name: Create Storage Container
        run: az storage container create --name tfstate --account-name webapptfstate143101a --auth-mode login

      - name: Release Blob Lease
        run: |
          lease_id=$(az storage blob lease acquire --account-name webapptfstate143101a --container-name tfstate --blob-name terraform.tfstate --lease-duration -1 --query leaseId -o tsv)
          az storage blob lease break --account-name webapptfstate143101a --container-name tfstate --blob-name terraform.tfstate --lease-id $lease_id

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Force Unlock
        run: terraform force-unlock -force 6e2ba91b-3939-e1e3-f066-55df4222cefb
        working-directory: terraform
        continue-on-error: true

      - name: Remove Resource Group from State
        run: terraform state rm azurerm_resource_group.backend
        working-directory: terraform
        continue-on-error: true

      - name: Remove Storage Account from State
        run: terraform state rm azurerm_storage_account.backend
        working-directory: terraform
        continue-on-error: true

      - name: Remove Storage Container from State
        run: terraform state rm azurerm_storage_container.backend
        working-directory: terraform
        continue-on-error: true

      - name: Import Resource Group
        run: terraform import -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}" azurerm_resource_group.backend /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/webapp-backend-rg
        working-directory: terraform

      - name: Import Storage Account
        run: terraform import -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}" azurerm_storage_account.backend /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/webapp-backend-rg/providers/Microsoft.Storage/storageAccounts/webapptfstate143101a
        working-directory: terraform

      - name: Import Storage Container
        run: terraform import -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}" azurerm_storage_container.backend /subscriptions/${{ secrets.AZURE_SUBSCRIPTION_ID }}/resourceGroups/webapp-backend-rg/providers/Microsoft.Storage/storageAccounts/webapptfstate143101a/blobServices/default/containers/tfstate
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -out "tfplan" -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" -var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}"
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -parallelism=10 -auto-approve "tfplan"
        working-directory: terraform